import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col w-full min-h-screen bg-primary-200 text-primary font-sans ${manropeSans.variable} antialiased selection:bg-emerald-300`}
      >
        <Navbar />
        <main className={`flex grow`}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
